// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/PacktPublishing/Domain-Driven-Design-with-GoLang/chapter8 (interfaces: CookieStockChecker,CardCharger,EmailSender)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCookieStockChecker is a mock of CookieStockChecker interface.
type MockCookieStockChecker struct {
	ctrl     *gomock.Controller
	recorder *MockCookieStockCheckerMockRecorder
}

// MockCookieStockCheckerMockRecorder is the mock recorder for MockCookieStockChecker.
type MockCookieStockCheckerMockRecorder struct {
	mock *MockCookieStockChecker
}

// NewMockCookieStockChecker creates a new mock instance.
func NewMockCookieStockChecker(ctrl *gomock.Controller) *MockCookieStockChecker {
	mock := &MockCookieStockChecker{ctrl: ctrl}
	mock.recorder = &MockCookieStockCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCookieStockChecker) EXPECT() *MockCookieStockCheckerMockRecorder {
	return m.recorder
}

// AmountInStock mocks base method.
func (m *MockCookieStockChecker) AmountInStock(arg0 context.Context) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AmountInStock", arg0)
	ret0, _ := ret[0].(int)
	return ret0
}

// AmountInStock indicates an expected call of AmountInStock.
func (mr *MockCookieStockCheckerMockRecorder) AmountInStock(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AmountInStock", reflect.TypeOf((*MockCookieStockChecker)(nil).AmountInStock), arg0)
}

// MockCardCharger is a mock of CardCharger interface.
type MockCardCharger struct {
	ctrl     *gomock.Controller
	recorder *MockCardChargerMockRecorder
}

// MockCardChargerMockRecorder is the mock recorder for MockCardCharger.
type MockCardChargerMockRecorder struct {
	mock *MockCardCharger
}

// NewMockCardCharger creates a new mock instance.
func NewMockCardCharger(ctrl *gomock.Controller) *MockCardCharger {
	mock := &MockCardCharger{ctrl: ctrl}
	mock.recorder = &MockCardChargerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCardCharger) EXPECT() *MockCardChargerMockRecorder {
	return m.recorder
}

// ChargeCard mocks base method.
func (m *MockCardCharger) ChargeCard(arg0 context.Context, arg1 string, arg2 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChargeCard", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChargeCard indicates an expected call of ChargeCard.
func (mr *MockCardChargerMockRecorder) ChargeCard(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChargeCard", reflect.TypeOf((*MockCardCharger)(nil).ChargeCard), arg0, arg1, arg2)
}

// MockEmailSender is a mock of EmailSender interface.
type MockEmailSender struct {
	ctrl     *gomock.Controller
	recorder *MockEmailSenderMockRecorder
}

// MockEmailSenderMockRecorder is the mock recorder for MockEmailSender.
type MockEmailSenderMockRecorder struct {
	mock *MockEmailSender
}

// NewMockEmailSender creates a new mock instance.
func NewMockEmailSender(ctrl *gomock.Controller) *MockEmailSender {
	mock := &MockEmailSender{ctrl: ctrl}
	mock.recorder = &MockEmailSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailSender) EXPECT() *MockEmailSenderMockRecorder {
	return m.recorder
}

// SendEmailReceipt mocks base method.
func (m *MockEmailSender) SendEmailReceipt(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendEmailReceipt", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendEmailReceipt indicates an expected call of SendEmailReceipt.
func (mr *MockEmailSenderMockRecorder) SendEmailReceipt(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEmailReceipt", reflect.TypeOf((*MockEmailSender)(nil).SendEmailReceipt), arg0, arg1)
}
