# builder image
FROM golang:1.18 as builder
RUN mkdir /build
COPY . /build/
WORKDIR /build
RUN CGO_ENABLED=0 GOOS=linux go build -a -o partnerships-api partnerships/main.go


# generate clean, final image for end users
FROM alpine
COPY --from=builder /build/partnerships-api .

# executable
ENTRYPOINT [ "./partnerships-api" ]
